on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Detekt
        run: ./gradlew detekt

      - name: Build
        run: ./gradlew build